[book]
title = "Trilium Wiki"
authors = ["smj"]
description = "Trilium 的中文文档."
language = "zh-CN"
multilingual = false
src = "src"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding
