[book]
title = "Trilium Wiki"
authors = ["smj"]
description = "Trilium 的中文文档."
language = "zh-CN"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/baddate/trilium-wiki"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/baddate/trilium-wiki/edit/master/{path}"
additional-css = ["theme/catppuccin.css", "theme/catppuccin-highlight.css"]
default-theme = "latte"
preferred-dark-theme = "mocha"
cname = "trilium.hyl.im"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding
